[package]
name = "crfsuite"
version = "0.4.3-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
libc = "0.2"
crfsuite-sys = { path = "crfsuite-sys" }

[workspace]

